# Generated by Django 3.1.4 on 2020-12-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitApp', '0002_auto_20201229_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField(default=0)),
                ('settled', models.BooleanField(default=False)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='splitApp.bill')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payer', to='splitApp.user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='splitApp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
