# Generated by Django 3.1.4 on 2020-12-31 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitApp', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='settled',
        ),
        migrations.AddField(
            model_name='group',
            name='group_icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note', to='splitApp.bill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
